apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/salihDIALLO/wordpress-k8s-project.git' # ou autre repo si tu as les manifests monitoring ailleurs
    targetRevision: HEAD
    path: 'monitoring'  # dossier où tu mets kube-prometheus-stack et configs monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
