apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  mariadb-root-password: rootpass
  mariadb-user: wpuser
  mariadb-password: wppass
  mariadb-database: wordpress
