apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 80        # port interne du service
      targetPort: 3000  # port du container Grafana
      nodePort: 30081   # port exposé sur le node
  selector:
    app: kube-prometheus-grafana
