apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordpress-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
  namespaceSelector:
    any: false
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
      # si ton exporter utilise un chemin/port différent, adapte ici
