apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
  namespaceSelector:
    any: false
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
      # MySQL/MariaDB exporter expose souvent sur 9104 ; adapte si besoin
