apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  env: prod
patchesStrategicMerge:
  - wordpress-prod-replicas.yaml
  - mysqld-prod-replicas.yaml
  - wordpress-pvc-prod.yaml
