apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: default
type: Opaque
stringData:
  mariadb-root-password: rootpass
  mariadb-database: wordpress
  mariadb-user: wpuser
  mariadb-password: wppass
  mariadb-exporter-dsn: "wpuser:wppass@tcp(mariadb:3306)/wordpress"
